// countries.ts
export const euCountries = [
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
];